language: r
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      r_check_args: '--use-valgrind'
    - os: osx
      osx_image: beta-xcode6.4
      disable_homebrew: true
      latex: false
  
addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - valgrind

cran: https://cran.rstudio.com/
r_packages:
   - covr
      
after_success:
   - Rscript -e 'library(covr); codecov()'      
      