language: r
cache: packages
warnings_are_errors: true

matrix:
  include:
    - os: osx
      osx_image: xcode8
      brew_packages: poppler
      latex: false
  
addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - valgrind